server:
  port: 8088

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/isales?serverTimezone=UTC&useSSL=false&&characterEncoding=UTF-8&allowMultiQueries=true&queryTimeout=2400
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

member.nickname: "悟空聊架构"
member.age: 18

#检测恶意IP，多少秒被出现多少次请求
ip_black_times: 10
ip_black_seconds: 10
#检测恶意IP，多少秒被出现多少次请求
user_black_times: 10
user_black_seconds: 10

jedis:
  url: 127.0.0.1
  password:
  port: 6379
  databasesIndex: 1
  maxTotal: 10000
  maxIdle: 5
  minIdle: 1
  maxWaitTime: 2000
  connectTimeout: 30