server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.18.1.141:3306/isales?serverTimezone=UTC&useSSL=false&&characterEncoding=UTF-8&allowMultiQueries=true&queryTimeout=2400
    username: isalesuser
    password: 'Isales_2019#wy'


member.nickname: "悟空聊架构"
member.age: 18

#检测恶意IP，多少秒被出现多少次请求
ip_black_times: 10
ip_black_seconds: 10
#检测恶意IP，多少秒被出现多少次请求
user_black_times: 10
user_black_seconds: 10

jedis:
  url: 172.18.1.141
  password:
  port: 6379
  databasesIndex: 1
  maxTotal: 10000
  maxIdle: 5
  minIdle: 1
  maxWaitTime: 2000
  connectTimeout: 30

