# \u7AEF\u53E3\u53F7
server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://172.18.1.141:3306/mdm?serverTimezone=UTC&useSSL=false&&characterEncoding=UTF-8&allowMultiQueries=true
    username: masuser
    password: ENC(toEhasjo/1psmaHxKBUyXi6NtaG3jZDC)


jasypt:
  encryptor:
    password: 123456